/*
 * This code was generated by ojc.
 */
import demo.*;
import java.util.*;


public class ErrorZero
{

    public ErrorZero()
    {
        super();
        trace.add( new java.lang.Integer( 3 ) );
    }

    public int methodAux( int x, int y )
    {
        trace.add( new java.lang.Integer( 4 ) );
        if (x > 0) {
            trace.add( new java.lang.Integer( 5 ) );
            return x + y;
        } else {
            trace.add( new java.lang.Integer( 6 ) );
            return 0;
        }
    }

    
    static java.util.Set trace = new java.util.HashSet();

    
    public static void newTrace()
    {
        trace = new java.util.HashSet();
    }

    
    public static java.util.Set getTrace()
    {
        return trace;
    }

}
