/*
 * This code was generated by ojc.
 */
import demo.*;
import java.util.*;


public class GetListPrimeNumber
{

    public GetListPrimeNumber()
    {
        trace.add( new java.lang.Integer( 1 ) );
    }

    public static void getList( int[] A )
    {
        trace.add( new java.lang.Integer( 2 ) );
        PrimeNumber oj = new PrimeNumber();
        int[] B = new int[oj.createListPrimeNumber( A ).size()];
        B[0] = 0;
        System.out.println( B[0] );
    }

    
    static java.util.Set trace = new java.util.HashSet();

    
    public static void newTrace()
    {
        trace = new java.util.HashSet();
    }

    
    public static java.util.Set getTrace()
    {
        return trace;
    }

}
